# Change these first
owner: northpolesec
repo: status

sites:
  - name: Coalmine
    url: coalmine.northpole.security
    port: 443
    check: "tcp-ping"
  - name: Push Service Staging (east)
    url: east1.staging.push.northpole.security
    port: 443
    check: "tcp-ping"
  - name: Push Service Staging (west)
    url: west1.staging.push.northpole.security
    port: 443
    check: "tcp-ping"
  - name: Push Service Staging (central)
    url: central1.staging.push.northpole.security
    port: 443
    check: "tcp-ping"
  - name: GAL
    url: gal.northpole.security
    port: 443
    check: "tcp-ping"

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/15 * * * *"

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.northpole.security
  logoUrl: https://github.com/northpolesec/santa/raw/main/docs/static/img/nps-logo-256.png
  favicon: https://northpole.security/favicon.png
  name: Status
  introTitle: "North Pole Security - Global Status"
  introMessage: This page shows the health and response times for North Pole Security's global services

i18n:
  footer: Powered by [Upptime](https://upptime.js.org)

